export const colors = {
  PRIMARY: "#FF603D",
  SECONDARY: "#F5A368",
  WHITE: "#FFFFFF",
  BACKGROUND_DEEP: "#FFD0C1",
  BACKGROUND_MID: "#FEE9E6",
  BACKGROUND_LIGHT: "#FFFAF9",
  TEXT_NORMAL: "#0E0301",
  TEXT_LIGHT: "#94969B",
  BORDER_LIGHT: "#D4D2E3",
}